### ISSUE TITLE
Fix Heroku button and deployment

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_wordpress_plugins#6]
- [x] The Heroku button is not a proper integrated badge, but just an uploaded image.
- [x] The Heroku deployment is not a deployment of this repository

**Comment by sopankhosla** [comment]
"Heroku deployed" is being taken from https://github.com/pussinboots/heroku-badge since Heroku itself does not provide the above-mentioned badge. 

The initial deployment is not of this repository but the later ones are. Please see [this](http://blog.loklak.net/using-heroku-wordpress-buildpack-to-test-loklak-integration-in-wordpress-plugins/). I will update the readme shortly as not able to have good internet connection for now.

@mariobehling

**Comment by sopu** [comment]
e5584ec. 
The readme has been updated with verbose steps to deploy to Heroku. 
Is it good to close?

**Comment by sopankhosla** [comment]
e5584ec. 
The readme has been updated with verbose steps to deploy to Heroku. 
Is it good to close? 
@mariobehling

**Comment by mariobehling** [comment]
Looks good. Thank you.

**Comment by sopankhosla** [comment]
Closing!
